In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
import os
import shutil
from pathlib import Path
import cv2
from glob import glob
from PIL import Image
from keras import layers
from keras import models
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
from sklearn.model_selection import StratifiedKFold

# 데이콘 이상치 탐색

**https://dacon.io/competitions/official/235894/overview/description**

In [4]:
path = "C:/Users/choij/Desktop/datasets/open/open/train/train/"
#train dataset 위치

In [5]:
path2 = 'C:/Users/choij/Desktop/datasets/open/open/test/test/'
#test 데이터셋 위치

## 데이터 전처리

In [8]:
df = pd.read_csv("C:/Users/choij/Desktop/datasets/open/open/train_df.csv")
df #1024 * 1024 * 3 형식의 이미지들

index  file_name       class state            label
0         0  10000.png  transistor  good  transistor-good
1         1  10001.png     capsule  good     capsule-good
2         2  10002.png  transistor  good  transistor-good
3         3  10003.png        wood  good        wood-good
4         4  10004.png      bottle  good      bottle-good
...     ...        ...         ...   ...              ...
4272   4272  14272.png  transistor  good  transistor-good
4273   4273  14273.png  transistor  good  transistor-good
4274   4274  14274.png        grid  good        grid-good
4275   4275  14275.png      zipper  good      zipper-good
4276   4276  14276.png       screw  good       screw-good

[4277 rows x 5 columns]

In [9]:
print(len(df['state'].value_counts())) 
print(len(df['class'].value_counts())) 
print(len(df['label'].value_counts())) # 88개의 클래스 분류

49
15
88


In [10]:
df['label'].value_counts()

hazelnut-good              391
screw-good                 320
carpet-good                280
pill-good                  267
grid-good                  264
                          ... 
cable-poke_insulation        5
pill-pill_type               5
transistor-damaged_case      5
transistor-bent_lead         5
wood-color                   4
Name: label, Length: 88, dtype: int64

In [11]:
df = df.drop(['class','state' , 'file_name'], axis = 1)

In [12]:
df.head()

index            label
0      0  transistor-good
1      1     capsule-good
2      2  transistor-good
3      3        wood-good
4      4      bottle-good

In [13]:
categories = np.unique(df['label'])
categories #클래스 집합 리스트

array(['bottle-broken_large', 'bottle-broken_small',
       'bottle-contamination', 'bottle-good', 'cable-bent_wire',
       'cable-cable_swap', 'cable-combined', 'cable-cut_inner_insulation',
       'cable-cut_outer_insulation', 'cable-good', 'cable-missing_cable',
       'cable-missing_wire', 'cable-poke_insulation', 'capsule-crack',
       'capsule-faulty_imprint', 'capsule-good', 'capsule-poke',
       'capsule-scratch', 'capsule-squeeze', 'carpet-color', 'carpet-cut',
       'carpet-good', 'carpet-hole', 'carpet-metal_contamination',
       'carpet-thread', 'grid-bent', 'grid-broken', 'grid-glue',
       'grid-good', 'grid-metal_contamination', 'grid-thread',
       'hazelnut-crack', 'hazelnut-cut', 'hazelnut-good', 'hazelnut-hole',
       'hazelnut-print', 'leather-color', 'leather-cut', 'leather-fold',
       'leather-glue', 'leather-good', 'leather-poke', 'metal_nut-bent',
       'metal_nut-color', 'metal_nut-flip', 'metal_nut-good',
       'metal_nut-scratch', 'pill-color', 'p

In [14]:
nb_classes = len(categories)
nb_classes
#https://velog.io/@jaehyeong/CNN-%EB%AA%A8%EB%8D%B8%EC%9D%84-%ED%86%B5%ED%95%9C-%EC%9E%90%EB%8F%99%EC%B0%A8-%EC%82%AC%EA%B3%A0-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%B6%84%EB%A5%98

88

In [15]:
base_dir = "C:/Users/choij/Desktop/datasets/open/open/train/small_train"

In [16]:
test_base_dir = "C:/Users/choij/Desktop/datasets/open/open/test/small_test"

In [79]:
os.mkdir(base_dir)

In [121]:
os.mkdir(test_base_dir)

In [17]:
fname_list = os.listdir(base_dir)

In [18]:
base = base_dir + '/'
base

'C:/Users/choij/Desktop/datasets/open/open/train/small_train/'

In [19]:
test_base = test_base_dir + '/'

In [80]:
for fname in categories:
    fnames = os.path.join(base_dir, fname)
    os.mkdir(fnames) # class 별로 폴더 생성

In [124]:
for fname in categories:
    fnames = os.path.join(test_base_dir, fname)
    os.mkdir(fnames)

In [20]:
format = [".jpg",".png",".jpeg","bmp",".JPG",".PNG","JPEG","BMP"]

In [50]:
for (path, dirs, files) in os.walk(path):
    for file in files:
        if file.endswith(tuple(format)):
            image = Image.open(path+"/"+file)
            image=image.resize((int(image.size[0]*0.2), int(image.size[1]*0.2)))
            image.save(path+"/"+file)
        else:
            print(path)
            print("InValid",file) # 훈련 파일크기 작게

In [51]:
for (path, dirs, files) in os.walk(path2):
    for file in files:
        if file.endswith(tuple(format)):
            image = Image.open(path+"/"+file)
            image=image.resize((int(image.size[0]*0.2), int(image.size[1]*0.2)))
            image.save(path+"/"+file)

        else:
            print(path)
            print("InValid",file) # 테스트 파일크기 작게

In [84]:
for idx in range(len(os.listdir(path))): #0~4277 반복하면서 훈련 이미지 복사
    index = 10000
    for fname in fname_list: #폴더 리스트 
        if df['label'][idx] == fname:
            index += idx
            index = str(index) + '.png' 
            path_dir = base_dir + '/'+ fname
            shutil.copyfile(path+index, path_dir + '/' + str(index) + '.png')

In [132]:
for idx in range(len(os.listdir(path2))): #0~4277 반복 테스트 이미지 복사
    index = 20000
    for fname in fname_list: #폴더 리스트 1개씩 흘음 
        if df['label'][idx] == fname:
            index += idx
            index = str(index) + '.png' 
            path_dir = test_base_dir + '/'+ fname
            shutil.copyfile(path2+index, path_dir + '/' + str(index))

In [22]:
def CustomModel():
    model = models.Sequential()

    model.add(layers.Conv2D(32, (5,5), activation = 'relu', input_shape = (150,150,3)))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2,2))

    model.add(layers.Conv2D(32, (5,5), activation = 'relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2,2))

    model.add(layers.Conv2D(64, (5,5), activation = 'relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2,2))

    model.add(layers.Conv2D(64, (1,1), activation = 'relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2,2))

    model.add(layers.Conv2D(128, (5,5), activation = 'relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2,2))
    model.add(layers.Dropout(0.5))

    model.add(layers.Flatten())
    model.add(layers.Dense(128, activation = 'relu'))
    model.add(layers.Dense(88, activation = 'softmax'))
    return model

In [23]:
image_w = 150
image_h = 150

X = []
Y = []

for idx, cat in enumerate(categories):
    label = [0 for i in range(nb_classes)]
    label[idx] = 1
    
    files = glob(base_dir + '/' + cat + '/*.png')
    for i, f in enumerate(files):
        img = Image.open(f)
        img = img.convert('RGB')
        img = img.resize((image_w, image_h))
        data = np.asarray(img)
        X.append(data)
        Y.append(label)
        if i % 10 ==0:
            print(i, '\n', data)


0 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
0 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 2

100 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
110 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

0 
 [[[ 84 114 138]
  [ 84 115 137]
  [ 82 111 132]
  ...
  [ 69  93 107]
  [ 61  80  91]
  [ 53  66  75]]

 [[ 84 116 141]
  [ 87 119 141]
  [ 82 110 129]
  ...
  [ 65  83  95]
  [ 58  72  82]
  [ 52  63  71]]

 [[ 82 116 143]
  [ 87 120 144]
  [ 80 107 126]
  ...
  [ 55  68  78]
  [ 49  59  65]
  [ 46  55  60]]

 ...

 [[ 72  95 114]
  [ 71  96 117]
  [ 69  94 115]
  ...
  [ 66  89 106]
  [ 64  85 103]
  [ 64  84 102]]

 [[ 75  99 118]
  [ 72  95 115]
  [ 67  89 106]
  ...
  [ 67  89 106]
  [ 63  84 101]
  [ 58  77  93]]

 [[ 75 100 118]
  [ 74  99 117]
  [ 72  97 114]
  ...
  [ 71  95 115]
  [ 66  87 106]
  [ 55  73  87]]]
0 
 [[[ 78 102 123]
  [ 81 108 135]
  [ 75 100 124]
  ...
  [ 61  78  97]
  [ 54  65  79]
  [ 47  55  67]]

 [[ 81 108 131]
  [ 81 111 140]
  [ 72  98 124]
  ...
  [ 62  80 101]
  [ 50  61  71]
  [ 43  50  59]]

 [[ 82 109 133]
  [ 80 108 138]
  [ 67  90 115]
  ...
  [ 60  75  95]
  [ 54  66  79]
  [ 53  65  78]]

 ...

 [[ 55  72  97]
  [ 54  73  98]
  [ 60  80 1

120 
 [[[ 81 110 138]
  [ 76 101 129]
  [ 65  83 106]
  ...
  [ 55  73 100]
  [ 61  81 108]
  [ 65  84 109]]

 [[ 73  95 122]
  [ 64  82 107]
  [ 63  80 100]
  ...
  [ 62  84 108]
  [ 58  77 104]
  [ 58  75  98]]

 [[ 65  81 102]
  [ 53  65  83]
  [ 63  81  98]
  ...
  [ 80 113 141]
  [ 65  89 118]
  [ 59  78 103]]

 ...

 [[ 57  72  92]
  [ 63  79  98]
  [ 78 102 125]
  ...
  [ 55  64  76]
  [ 67  85 105]
  [ 85 116 143]]

 [[ 60  78  98]
  [ 72  95 117]
  [ 84 114 141]
  ...
  [ 61  74  92]
  [ 71  92 115]
  [ 84 114 144]]

 [[ 73  99 124]
  [ 82 112 139]
  [ 82 109 134]
  ...
  [ 66  82 103]
  [ 83 111 141]
  [103 149 187]]]
130 
 [[[ 52  66  79]
  [ 47  58  67]
  [ 42  51  59]
  ...
  [ 63  85 105]
  [ 59  81 100]
  [ 60  82 104]]

 [[ 48  60  70]
  [ 50  63  74]
  [ 49  62  73]
  ...
  [ 67  92 114]
  [ 60  84 105]
  [ 59  83 104]]

 [[ 56  73  86]
  [ 56  70  82]
  [ 52  65  76]
  ...
  [ 70  96 116]
  [ 64  89 108]
  [ 58  80  98]]

 ...

 [[ 47  59  69]
  [ 43  52  61]
  [ 42  

0 
 [[[232 230 228]
  [229 232 228]
  [230 231 227]
  ...
  [224 222 226]
  [225 224 226]
  [226 224 223]]

 [[227 229 227]
  [229 230 227]
  [229 229 229]
  ...
  [224 223 226]
  [225 225 226]
  [224 222 223]]

 [[227 227 227]
  [229 230 227]
  [227 229 228]
  ...
  [226 224 224]
  [227 224 224]
  [225 222 225]]

 ...

 [[225 229 219]
  [225 229 220]
  [221 226 218]
  ...
  [214 214 209]
  [214 213 210]
  [213 211 210]]

 [[225 229 219]
  [223 228 219]
  [224 227 218]
  ...
  [214 214 210]
  [211 214 211]
  [210 211 210]]

 [[224 226 220]
  [223 226 220]
  [225 227 217]
  ...
  [210 211 209]
  [212 212 211]
  [211 212 210]]]
10 
 [[[211 216 217]
  [211 214 218]
  [208 214 219]
  ...
  [208 209 214]
  [209 211 213]
  [209 210 213]]

 [[212 216 218]
  [210 214 216]
  [209 215 217]
  ...
  [208 210 215]
  [207 210 212]
  [207 209 213]]

 [[212 216 218]
  [211 215 218]
  [210 214 216]
  ...
  [209 211 215]
  [206 210 213]
  [206 209 213]]

 ...

 [[206 211 207]
  [207 214 208]
  [206 213 

170 
 [[[217 220 221]
  [217 219 221]
  [218 218 220]
  ...
  [215 214 220]
  [214 214 218]
  [216 214 217]]

 [[216 219 222]
  [215 219 221]
  [217 216 218]
  ...
  [214 214 218]
  [211 212 218]
  [213 213 217]]

 [[217 217 221]
  [215 217 219]
  [213 216 218]
  ...
  [214 216 218]
  [211 213 217]
  [214 215 220]]

 ...

 [[209 213 210]
  [210 215 209]
  [211 215 210]
  ...
  [201 206 205]
  [203 206 206]
  [203 205 205]]

 [[210 214 209]
  [210 213 209]
  [211 215 211]
  ...
  [202 207 206]
  [203 204 205]
  [203 205 205]]

 [[212 217 210]
  [210 214 208]
  [211 215 209]
  ...
  [204 207 205]
  [203 206 205]
  [203 205 208]]]
180 
 [[[231 228 226]
  [228 227 227]
  [230 229 230]
  ...
  [227 225 225]
  [226 224 226]
  [226 224 226]]

 [[229 228 227]
  [230 227 227]
  [229 230 228]
  ...
  [228 226 225]
  [224 224 223]
  [225 224 224]]

 [[229 228 228]
  [229 230 225]
  [228 230 224]
  ...
  [228 226 226]
  [225 225 225]
  [225 224 226]]

 ...

 [[220 223 215]
  [220 223 215]
  [219 2

50 
 [[[ 61  54  60]
  [ 43  41  48]
  [ 31  34  42]
  ...
  [ 34  32  38]
  [ 39  34  40]
  [ 73  67  70]]

 [[ 68  61  66]
  [ 68  65  70]
  [ 84  86  89]
  ...
  [ 57  48  54]
  [ 54  46  51]
  [ 77  71  73]]

 [[ 75  68  72]
  [ 59  54  59]
  [ 61  55  60]
  ...
  [ 35  29  36]
  [ 45  38  42]
  [ 81  75  77]]

 ...

 [[ 44  43  49]
  [ 66  65  70]
  [112 109 110]
  ...
  [ 57  56  61]
  [ 70  67  71]
  [ 52  50  57]]

 [[ 30  28  35]
  [ 56  56  62]
  [103 101 102]
  ...
  [ 39  37  43]
  [ 85  78  80]
  [ 44  44  50]]

 [[ 57  55  61]
  [ 92  91  94]
  [117 115 114]
  ...
  [ 57  52  55]
  [ 94  86  88]
  [ 66  62  67]]]
60 
 [[[ 63  60  64]
  [ 63  57  61]
  [ 45  42  47]
  ...
  [ 64  61  65]
  [ 29  30  36]
  [ 52  49  51]]

 [[ 40  40  45]
  [ 55  50  55]
  [ 37  37  43]
  ...
  [ 63  59  64]
  [ 49  45  50]
  [ 62  58  61]]

 [[ 48  44  50]
  [ 54  49  54]
  [ 57  54  58]
  ...
  [ 65  59  64]
  [ 68  64  66]
  [ 86  84  85]]

 ...

 [[107 105 103]
  [115 113 110]
  [119 116

210 
 [[[ 53  46  51]
  [ 41  35  40]
  [ 66  62  68]
  ...
  [ 54  52  54]
  [ 81  76  79]
  [ 42  37  43]]

 [[ 43  40  44]
  [ 29  31  39]
  [ 71  69  74]
  ...
  [ 79  77  79]
  [ 86  82  84]
  [ 46  40  46]]

 [[ 53  50  54]
  [ 63  61  68]
  [ 86  81  83]
  ...
  [102  96  96]
  [ 89  83  86]
  [ 54  47  51]]

 ...

 [[ 87  81  83]
  [ 60  55  57]
  [ 51  46  52]
  ...
  [ 78  71  74]
  [ 70  63  66]
  [ 84  75  78]]

 [[ 95  90  90]
  [ 81  74  76]
  [ 67  62  66]
  ...
  [ 72  66  70]
  [ 58  53  58]
  [ 70  65  68]]

 [[ 96  92  92]
  [ 73  68  71]
  [ 68  62  67]
  ...
  [ 57  52  57]
  [ 48  45  49]
  [ 80  77  78]]]
220 
 [[[ 70  67  70]
  [ 84  81  83]
  [ 91  84  88]
  ...
  [ 61  52  58]
  [ 92  88  89]
  [102  97  96]]

 [[ 36  37  42]
  [ 68  66  71]
  [ 74  69  73]
  ...
  [ 51  44  49]
  [ 71  66  67]
  [ 80  73  74]]

 [[ 53  55  60]
  [ 80  79  83]
  [ 85  79  84]
  ...
  [ 35  31  37]
  [ 39  36  41]
  [ 75  69  72]]

 ...

 [[ 82  71  74]
  [ 68  63  68]
  [104  

40 
 [[[ 53  53  53]
  [ 82  82  82]
  [109 109 109]
  ...
  [ 60  60  60]
  [ 81  81  81]
  [ 95  95  95]]

 [[ 51  51  51]
  [ 43  43  43]
  [ 59  59  59]
  ...
  [ 62  62  62]
  [ 82  82  82]
  [ 99  99  99]]

 [[ 91  91  91]
  [ 62  62  62]
  [ 49  49  49]
  ...
  [ 65  65  65]
  [ 78  78  78]
  [ 98  98  98]]

 ...

 [[115 115 115]
  [ 84  84  84]
  [ 56  56  56]
  ...
  [168 168 168]
  [164 164 164]
  [144 144 144]]

 [[121 121 121]
  [107 107 107]
  [ 63  63  63]
  ...
  [163 163 163]
  [159 159 159]
  [154 154 154]]

 [[125 125 125]
  [117 117 117]
  [ 72  72  72]
  ...
  [167 167 167]
  [160 160 160]
  [157 157 157]]]
50 
 [[[ 71  71  71]
  [ 49  49  49]
  [ 51  51  51]
  ...
  [131 131 131]
  [134 134 134]
  [134 134 134]]

 [[122 122 122]
  [ 92  92  92]
  [ 59  59  59]
  ...
  [128 128 128]
  [130 130 130]
  [130 130 130]]

 [[138 138 138]
  [131 131 131]
  [102 102 102]
  ...
  [127 127 127]
  [128 128 128]
  [129 129 129]]

 ...

 [[108 108 108]
  [ 60  60  60]
  [ 74  74

190 
 [[[151 151 151]
  [151 151 151]
  [135 135 135]
  ...
  [ 72  72  72]
  [ 76  76  76]
  [103 103 103]]

 [[162 162 162]
  [160 160 160]
  [157 157 157]
  ...
  [110 110 110]
  [140 140 140]
  [156 156 156]]

 [[171 171 171]
  [168 168 168]
  [161 161 161]
  ...
  [162 162 162]
  [166 166 166]
  [166 166 166]]

 ...

 [[158 158 158]
  [169 169 169]
  [176 176 176]
  ...
  [ 69  69  69]
  [ 58  58  58]
  [ 60  60  60]]

 [[145 145 145]
  [168 168 168]
  [176 176 176]
  ...
  [107 107 107]
  [ 96  96  96]
  [ 73  73  73]]

 [[ 94  94  94]
  [137 137 137]
  [164 164 164]
  ...
  [ 77  77  77]
  [ 87  87  87]
  [ 94  94  94]]]
200 
 [[[127 127 127]
  [111 111 111]
  [ 93  93  93]
  ...
  [ 86  86  86]
  [ 90  90  90]
  [123 123 123]]

 [[123 123 123]
  [ 99  99  99]
  [ 96  96  96]
  ...
  [ 88  88  88]
  [ 84  84  84]
  [120 120 120]]

 [[102 102 102]
  [ 89  89  89]
  [ 80  80  80]
  ...
  [ 92  92  92]
  [ 77  77  77]
  [115 115 115]]

 ...

 [[ 85  85  85]
  [ 73  73  73]
  [ 54  

20 
 [[[43 42 48]
  [43 43 47]
  [43 42 46]
  ...
  [40 41 46]
  [39 40 45]
  [41 41 46]]

 [[42 43 47]
  [44 42 48]
  [42 41 46]
  ...
  [41 40 45]
  [42 40 45]
  [41 41 46]]

 [[43 42 49]
  [42 41 47]
  [41 42 47]
  ...
  [41 40 45]
  [42 41 45]
  [41 40 46]]

 ...

 [[43 46 49]
  [44 45 48]
  [44 45 48]
  ...
  [41 40 44]
  [40 41 44]
  [40 40 44]]

 [[44 46 49]
  [44 46 48]
  [44 45 49]
  ...
  [40 40 43]
  [40 40 44]
  [39 41 44]]

 [[47 47 50]
  [45 47 50]
  [42 44 47]
  ...
  [41 40 44]
  [41 41 45]
  [40 40 44]]]
30 
 [[[37 37 42]
  [37 36 41]
  [35 36 41]
  ...
  [37 37 42]
  [38 37 42]
  [38 37 42]]

 [[38 37 42]
  [37 36 40]
  [35 35 40]
  ...
  [37 36 43]
  [36 36 40]
  [37 36 41]]

 [[36 36 40]
  [37 37 40]
  [35 36 41]
  ...
  [38 36 42]
  [38 37 40]
  [36 37 41]]

 ...

 [[41 44 43]
  [41 43 44]
  [40 43 43]
  ...
  [37 37 39]
  [39 38 40]
  [38 37 40]]

 [[41 44 44]
  [40 44 44]
  [40 43 43]
  ...
  [39 38 42]
  [38 38 42]
  [37 37 40]]

 [[41 45 44]
  [41 43 44]
  [41 

220 
 [[[35 35 39]
  [35 34 38]
  [34 34 38]
  ...
  [28 28 34]
  [27 27 32]
  [28 27 32]]

 [[35 34 38]
  [34 34 38]
  [33 33 37]
  ...
  [28 30 33]
  [28 29 33]
  [28 29 32]]

 [[35 34 39]
  [36 34 39]
  [34 34 38]
  ...
  [30 29 34]
  [29 30 34]
  [30 30 33]]

 ...

 [[37 38 41]
  [38 37 40]
  [38 37 41]
  ...
  [38 38 40]
  [38 37 38]
  [37 36 39]]

 [[39 38 41]
  [37 37 40]
  [37 36 39]
  ...
  [37 37 39]
  [38 36 40]
  [37 35 39]]

 [[40 39 42]
  [37 37 41]
  [37 37 40]
  ...
  [35 35 38]
  [35 35 39]
  [36 36 39]]]
230 
 [[[35 35 39]
  [37 37 40]
  [37 37 41]
  ...
  [36 35 40]
  [35 35 39]
  [33 33 39]]

 [[36 35 40]
  [38 38 42]
  [38 37 42]
  ...
  [36 36 41]
  [35 35 40]
  [36 34 38]]

 [[36 36 41]
  [37 37 41]
  [37 37 42]
  ...
  [36 34 38]
  [36 36 40]
  [36 36 40]]

 ...

 [[42 45 44]
  [42 43 43]
  [42 42 44]
  ...
  [38 37 39]
  [38 36 41]
  [38 37 40]]

 [[42 44 44]
  [43 44 45]
  [42 42 43]
  ...
  [37 36 39]
  [39 38 41]
  [39 39 41]]

 [[43 45 44]
  [42 44 44]
  [4

0 
 [[[110  73  61]
  [112  74  62]
  [115  75  63]
  ...
  [119  78  66]
  [ 99  63  53]
  [106  68  57]]

 [[ 96  62  53]
  [ 99  64  55]
  [105  68  57]
  ...
  [111  72  61]
  [104  66  56]
  [107  69  58]]

 [[105  70  60]
  [110  73  62]
  [105  70  59]
  ...
  [104  68  57]
  [100  64  53]
  [107  69  57]]

 ...

 [[ 91  62  54]
  [ 86  57  49]
  [ 97  61  51]
  ...
  [ 84  54  46]
  [ 93  60  52]
  [ 93  60  52]]

 [[ 96  65  56]
  [ 86  56  48]
  [ 91  60  50]
  ...
  [ 90  59  52]
  [ 79  52  46]
  [ 84  55  48]]

 [[ 96  65  57]
  [ 86  57  51]
  [102  68  59]
  ...
  [105  69  59]
  [ 92  62  54]
  [ 80  52  46]]]
0 
 [[[ 81  54  48]
  [ 87  58  50]
  [ 92  61  52]
  ...
  [103  66  56]
  [100  64  55]
  [ 91  59  51]]

 [[ 94  63  52]
  [ 94  62  52]
  [ 89  58  49]
  ...
  [ 93  59  50]
  [100  64  53]
  [102  65  54]]

 [[ 87  56  48]
  [ 91  60  51]
  [ 91  61  52]
  ...
  [ 97  62  51]
  [100  63  53]
  [ 97  62  51]]

 ...

 [[ 78  52  45]
  [ 92  62  53]
  [ 99  67  

140 
 [[[ 92  63  53]
  [ 94  63  54]
  [ 95  65  55]
  ...
  [ 93  60  50]
  [ 94  61  51]
  [ 88  58  48]]

 [[ 84  57  48]
  [ 88  59  50]
  [ 96  64  55]
  ...
  [ 89  58  48]
  [ 88  57  47]
  [ 97  64  52]]

 [[ 89  60  51]
  [ 85  57  49]
  [ 95  62  53]
  ...
  [116  78  62]
  [102  69  57]
  [ 94  61  49]]

 ...

 [[ 72  50  44]
  [ 78  55  47]
  [ 78  54  47]
  ...
  [ 83  55  47]
  [ 79  52  45]
  [ 81  53  46]]

 [[ 76  52  45]
  [ 78  54  47]
  [ 80  55  47]
  ...
  [100  67  56]
  [ 89  60  50]
  [ 76  51  44]]

 [[ 77  54  46]
  [ 78  54  47]
  [ 83  58  50]
  ...
  [ 92  62  52]
  [ 94  64  53]
  [ 88  59  50]]]
150 
 [[[ 77  51  44]
  [ 88  59  50]
  [ 84  56  48]
  ...
  [ 94  62  52]
  [ 96  64  53]
  [102  66  54]]

 [[ 77  52  44]
  [ 77  52  44]
  [ 89  60  50]
  ...
  [ 98  64  53]
  [100  66  56]
  [ 91  60  49]]

 [[ 75  50  43]
  [ 81  55  46]
  [ 82  55  46]
  ...
  [ 91  58  49]
  [ 97  63  54]
  [ 92  61  51]]

 ...

 [[ 71  49  43]
  [ 77  53  46]
  [ 77  

60 
 [[[25 25 30]
  [24 25 29]
  [25 24 29]
  ...
  [23 23 28]
  [23 23 30]
  [23 23 30]]

 [[25 24 29]
  [24 24 31]
  [24 24 31]
  ...
  [23 23 28]
  [23 23 28]
  [23 23 28]]

 [[23 24 31]
  [24 24 31]
  [24 24 31]
  ...
  [24 23 29]
  [22 24 28]
  [24 23 28]]

 ...

 [[24 25 31]
  [24 25 31]
  [24 25 31]
  ...
  [22 24 31]
  [23 23 30]
  [24 23 29]]

 [[24 25 31]
  [24 25 31]
  [25 25 31]
  ...
  [24 23 30]
  [23 23 29]
  [23 23 31]]

 [[24 25 31]
  [25 27 31]
  [25 25 31]
  ...
  [24 23 31]
  [23 24 30]
  [23 24 29]]]
70 
 [[[24 23 29]
  [24 22 28]
  [23 23 29]
  ...
  [24 23 29]
  [23 22 29]
  [23 22 29]]

 [[24 22 30]
  [23 23 30]
  [22 23 30]
  ...
  [23 22 29]
  [23 22 27]
  [21 22 27]]

 [[23 23 28]
  [23 23 30]
  [22 23 29]
  ...
  [22 22 28]
  [22 22 28]
  [22 22 28]]

 ...

 [[24 23 31]
  [23 22 29]
  [23 23 28]
  ...
  [23 22 28]
  [23 22 29]
  [22 23 28]]

 [[23 22 30]
  [23 22 30]
  [23 22 29]
  ...
  [22 22 30]
  [23 22 29]
  [23 23 28]]

 [[23 23 29]
  [22 23 30]
  [22 

10 
 [[[23 23 29]
  [23 22 29]
  [23 22 29]
  ...
  [23 23 28]
  [22 22 29]
  [22 22 28]]

 [[22 22 30]
  [23 22 28]
  [22 23 29]
  ...
  [23 22 28]
  [22 22 29]
  [24 23 29]]

 [[22 23 29]
  [23 22 29]
  [21 22 28]
  ...
  [21 22 28]
  [23 22 29]
  [25 23 30]]

 ...

 [[23 23 30]
  [22 22 29]
  [22 22 29]
  ...
  [22 22 27]
  [22 22 27]
  [23 22 27]]

 [[23 23 31]
  [22 22 29]
  [22 22 28]
  ...
  [22 22 28]
  [21 22 28]
  [23 22 28]]

 [[23 22 29]
  [22 22 29]
  [22 22 28]
  ...
  [23 22 28]
  [23 23 29]
  [22 22 29]]]
0 
 [[[14 16 27]
  [14 15 26]
  [14 14 25]
  ...
  [14 14 25]
  [14 14 24]
  [13 13 23]]

 [[15 14 26]
  [15 14 25]
  [15 14 24]
  ...
  [14 14 24]
  [13 13 24]
  [13 13 23]]

 [[15 14 26]
  [14 13 23]
  [14 14 25]
  ...
  [14 13 24]
  [14 13 23]
  [13 13 23]]

 ...

 [[14 14 24]
  [14 14 25]
  [15 15 27]
  ...
  [14 15 24]
  [15 15 25]
  [14 14 25]]

 [[14 14 25]
  [15 14 25]
  [14 14 25]
  ...
  [15 15 25]
  [15 15 25]
  [15 15 25]]

 [[15 14 24]
  [15 15 25]
  [14 1

120 
 [[[16 16 29]
  [16 16 27]
  [16 16 28]
  ...
  [16 15 27]
  [15 15 26]
  [15 16 27]]

 [[16 17 27]
  [15 16 27]
  [15 16 27]
  ...
  [15 15 26]
  [15 14 26]
  [14 14 25]]

 [[17 17 28]
  [16 16 28]
  [15 16 27]
  ...
  [15 15 26]
  [15 15 27]
  [15 15 26]]

 ...

 [[15 15 26]
  [15 15 26]
  [16 15 26]
  ...
  [15 15 27]
  [15 16 27]
  [15 15 25]]

 [[15 15 28]
  [15 15 26]
  [15 15 26]
  ...
  [16 16 27]
  [15 15 26]
  [14 15 26]]

 [[15 15 27]
  [16 15 26]
  [16 16 26]
  ...
  [15 15 25]
  [15 15 27]
  [15 15 26]]]
130 
 [[[15 15 25]
  [16 16 27]
  [16 16 26]
  ...
  [14 14 23]
  [15 15 24]
  [15 16 26]]

 [[15 15 26]
  [15 15 26]
  [15 16 25]
  ...
  [15 14 24]
  [16 16 26]
  [15 16 25]]

 [[15 15 26]
  [15 14 25]
  [15 14 25]
  ...
  [14 14 23]
  [13 14 24]
  [14 14 25]]

 ...

 [[15 16 26]
  [15 15 26]
  [16 16 26]
  ...
  [14 16 25]
  [15 15 24]
  [15 15 24]]

 [[16 16 28]
  [15 15 27]
  [15 15 25]
  ...
  [15 16 24]
  [14 15 24]
  [14 15 26]]

 [[16 16 27]
  [15 16 26]
  [1

40 
 [[[199 199 199]
  [200 200 200]
  [201 201 201]
  ...
  [204 204 204]
  [203 203 203]
  [203 203 203]]

 [[199 199 199]
  [199 199 199]
  [199 199 199]
  ...
  [203 203 203]
  [202 202 202]
  [203 203 203]]

 [[201 201 201]
  [201 201 201]
  [201 201 201]
  ...
  [203 203 203]
  [203 203 203]
  [203 203 203]]

 ...

 [[200 200 200]
  [200 200 200]
  [199 199 199]
  ...
  [195 195 195]
  [195 195 195]
  [196 196 196]]

 [[201 201 201]
  [202 202 202]
  [201 201 201]
  ...
  [197 197 197]
  [197 197 197]
  [196 196 196]]

 [[200 200 200]
  [201 201 201]
  [199 199 199]
  ...
  [195 195 195]
  [194 194 194]
  [195 195 195]]]
50 
 [[[200 200 200]
  [201 201 201]
  [201 201 201]
  ...
  [203 203 203]
  [201 201 201]
  [202 202 202]]

 [[201 201 201]
  [201 201 201]
  [202 202 202]
  ...
  [203 203 203]
  [201 201 201]
  [203 203 203]]

 [[199 199 199]
  [201 201 201]
  [201 201 201]
  ...
  [201 201 201]
  [203 203 203]
  [203 203 203]]

 ...

 [[197 197 197]
  [198 198 198]
  [198 198

180 
 [[[191 191 191]
  [191 191 191]
  [191 191 191]
  ...
  [200 200 200]
  [199 199 199]
  [199 199 199]]

 [[191 191 191]
  [192 192 192]
  [191 191 191]
  ...
  [198 198 198]
  [199 199 199]
  [199 199 199]]

 [[190 190 190]
  [191 191 191]
  [192 192 192]
  ...
  [198 198 198]
  [199 199 199]
  [197 197 197]]

 ...

 [[198 198 198]
  [199 199 199]
  [199 199 199]
  ...
  [201 201 201]
  [200 200 200]
  [202 202 202]]

 [[199 199 199]
  [200 200 200]
  [199 199 199]
  ...
  [200 200 200]
  [200 200 200]
  [202 202 202]]

 [[199 199 199]
  [199 199 199]
  [197 197 197]
  ...
  [201 201 201]
  [201 201 201]
  [199 199 199]]]
190 
 [[[194 194 194]
  [194 194 194]
  [194 194 194]
  ...
  [203 203 203]
  [205 205 205]
  [204 204 204]]

 [[194 194 194]
  [194 194 194]
  [193 193 193]
  ...
  [202 202 202]
  [202 202 202]
  [204 204 204]]

 [[194 194 194]
  [193 193 193]
  [195 195 195]
  ...
  [203 203 203]
  [203 203 203]
  [203 203 203]]

 ...

 [[201 201 201]
  [202 202 202]
  [202 2

10 
 [[[204 204 204]
  [204 204 204]
  [203 203 203]
  ...
  [199 199 199]
  [197 197 197]
  [203 203 203]]

 [[205 205 205]
  [204 204 204]
  [203 203 203]
  ...
  [203 203 203]
  [205 205 205]
  [206 206 206]]

 [[206 206 206]
  [204 204 204]
  [204 204 204]
  ...
  [203 203 203]
  [205 205 205]
  [205 205 205]]

 ...

 [[209 209 209]
  [209 209 209]
  [209 209 209]
  ...
  [198 198 198]
  [198 198 198]
  [196 196 196]]

 [[209 209 209]
  [208 208 208]
  [209 209 209]
  ...
  [198 198 198]
  [198 198 198]
  [196 196 196]]

 [[209 209 209]
  [209 209 209]
  [208 208 208]
  ...
  [199 199 199]
  [199 199 199]
  [198 198 198]]]
0 
 [[[207 207 207]
  [208 208 208]
  [206 206 206]
  ...
  [205 205 205]
  [204 204 204]
  [204 204 204]]

 [[209 209 209]
  [208 208 208]
  [208 208 208]
  ...
  [206 206 206]
  [206 206 206]
  [205 205 205]]

 [[210 210 210]
  [207 207 207]
  [208 208 208]
  ...
  [205 205 205]
  [205 205 205]
  [205 205 205]]

 ...

 [[211 211 211]
  [212 212 212]
  [210 210 

100 
 [[[179 194 180]
  [126 135 123]
  [ 83  86  75]
  ...
  [158 165 159]
  [117 122 113]
  [ 86  86  82]]

 [[171 186 172]
  [131 141 130]
  [ 83  86  78]
  ...
  [137 140 136]
  [125 128 121]
  [117 118 112]]

 [[146 156 141]
  [107 112 101]
  [ 91  96  84]
  ...
  [ 96  94  93]
  [105 103 101]
  [119 118 117]]

 ...

 [[156 166 153]
  [125 129 118]
  [132 137 124]
  ...
  [ 59  60  58]
  [ 59  60  60]
  [ 63  62  64]]

 [[135 139 127]
  [138 145 133]
  [151 158 147]
  ...
  [ 59  60  60]
  [ 63  63  63]
  [ 75  74  75]]

 [[100 102  91]
  [114 117 104]
  [135 141 128]
  ...
  [ 65  65  65]
  [ 78  77  77]
  [117 117 117]]]
110 
 [[[146 150 136]
  [ 96  98  86]
  [ 88  86  75]
  ...
  [127 125 117]
  [115 110 103]
  [128 124 118]]

 [[154 158 146]
  [140 148 134]
  [133 135 120]
  ...
  [107 106 100]
  [103  96  93]
  [124 120 114]]

 [[145 150 138]
  [163 172 158]
  [165 170 156]
  ...
  [ 88  85  82]
  [ 85  81  80]
  [115 110 107]]

 ...

 [[138 139 127]
  [131 134 123]
  [154 1

0 
 [[[ 97  98  90]
  [ 95  98  88]
  [101 105  95]
  ...
  [184 189 185]
  [151 154 144]
  [130 129 118]]

 [[107 113 101]
  [100 103  92]
  [ 88  92  83]
  ...
  [188 195 192]
  [154 156 146]
  [123 119 113]]

 [[139 150 139]
  [130 138 124]
  [ 94  99  89]
  ...
  [187 194 191]
  [160 162 156]
  [136 133 125]]

 ...

 [[107 108 102]
  [127 130 120]
  [108 110 102]
  ...
  [ 85  81  80]
  [101  97  96]
  [125 124 121]]

 [[105 105  98]
  [111 116 105]
  [ 95  98  91]
  ...
  [ 86  84  83]
  [ 92  90  88]
  [ 99  96  95]]

 [[ 82  80  75]
  [ 82  82  77]
  [ 80  81  76]
  ...
  [ 72  70  70]
  [ 74  72  73]
  [ 79  77  78]]]
0 
 [[[18 17 25]
  [19 18 25]
  [19 18 25]
  ...
  [16 17 22]
  [17 16 23]
  [16 17 22]]

 [[19 18 24]
  [19 17 24]
  [18 18 25]
  ...
  [16 16 22]
  [15 16 22]
  [15 16 22]]

 [[19 18 25]
  [18 18 25]
  [19 17 25]
  ...
  [16 17 22]
  [15 17 22]
  [16 16 23]]

 ...

 [[17 17 24]
  [17 17 23]
  [17 17 23]
  ...
  [19 19 24]
  [18 18 25]
  [19 18 24]]

 [[17 17 23]

30 
 [[[146 100  90]
  [146 100  89]
  [149 101  90]
  ...
  [159 108  95]
  [157 107  94]
  [154 106  93]]

 [[145 100  89]
  [148 102  89]
  [151 104  91]
  ...
  [159 107  93]
  [158 107  93]
  [156 106  92]]

 [[147 101  91]
  [151 104  91]
  [154 105  91]
  ...
  [162 109  94]
  [160 108  92]
  [156 106  91]]

 ...

 [[139  96  85]
  [139  96  85]
  [140  96  85]
  ...
  [160 107  92]
  [160 107  93]
  [157 105  91]]

 [[140  96  85]
  [137  94  83]
  [139  95  85]
  ...
  [161 108  91]
  [161 108  93]
  [160 106  92]]

 [[140  95  84]
  [138  94  82]
  [140  96  84]
  ...
  [159 105  90]
  [157 104  88]
  [157 105  90]]]
40 
 [[[111  80  71]
  [ 63  51  50]
  [ 44  40  42]
  ...
  [148 103  89]
  [150 105  90]
  [148 106  90]]

 [[135  94  82]
  [102  75  66]
  [ 62  53  52]
  ...
  [129  89  78]
  [151 106  90]
  [151 106  90]]

 [[145 101  87]
  [135  94  82]
  [108  80  71]
  ...
  [133  91  77]
  [146 103  87]
  [151 106  90]]

 ...

 [[135  95  84]
  [135  95  85]
  [134  96

160 
 [[[143  98  87]
  [143  99  86]
  [147 101  88]
  ...
  [149 104  90]
  [146 102  89]
  [143 101  88]]

 [[143  97  86]
  [142  98  85]
  [144  99  87]
  ...
  [150 103  90]
  [147 103  90]
  [146 103  90]]

 [[140  96  85]
  [141  97  84]
  [141  97  84]
  ...
  [150 104  91]
  [149 103  90]
  [150 104  90]]

 ...

 [[142  97  86]
  [142  98  85]
  [138  95  83]
  ...
  [147 102  88]
  [146 100  88]
  [149 103  91]]

 [[140  97  84]
  [140  97  84]
  [138  96  84]
  ...
  [148 103  90]
  [146 101  88]
  [149 102  89]]

 [[136  93  81]
  [139  96  81]
  [140  95  82]
  ...
  [150 103  87]
  [147 101  87]
  [146 101  88]]]
170 
 [[[160 113 102]
  [161 116 103]
  [160 114 101]
  ...
  [155 108  92]
  [155 109  95]
  [157 110  95]]

 [[156 111  99]
  [158 113 100]
  [157 112 100]
  ...
  [157 110  95]
  [158 111  96]
  [158 111  95]]

 [[154 110  97]
  [159 113  99]
  [158 113 100]
  ...
  [158 111  95]
  [159 112  96]
  [158 111  96]]

 ...

 [[143 101  91]
  [143 101  91]
  [143 1

60 
 [[[178 138 105]
  [170 126  93]
  [168 122  90]
  ...
  [143  98  73]
  [134  86  65]
  [142 100  76]]

 [[182 141 106]
  [174 129  94]
  [168 122  89]
  ...
  [145  99  75]
  [137  89  66]
  [144 101  77]]

 [[184 141 107]
  [180 133  98]
  [174 126  93]
  ...
  [145  99  75]
  [137  89  66]
  [147 103  78]]

 ...

 [[188 152 109]
  [181 140  99]
  [175 137  98]
  ...
  [149 108  79]
  [139 102  75]
  [129  94  71]]

 [[183 147 106]
  [176 137  96]
  [173 137  99]
  ...
  [144 104  76]
  [141 104  76]
  [126  92  69]]

 [[174 137  98]
  [170 131  92]
  [170 132  94]
  ...
  [140 102  75]
  [141 102  76]
  [123  91  69]]]
70 
 [[[188 147 115]
  [195 158 123]
  [176 133 102]
  ...
  [127  91  70]
  [142 101  76]
  [128  90  69]]

 [[190 149 115]
  [197 158 122]
  [172 127  96]
  ...
  [132  94  73]
  [146 104  79]
  [131  92  70]]

 [[196 155 119]
  [202 161 126]
  [171 125  94]
  ...
  [134  96  72]
  [149 106  80]
  [130  92  70]]

 ...

 [[192 150 106]
  [198 158 113]
  [202 167

210 
 [[[185 133 101]
  [175 123  94]
  [175 124  95]
  ...
  [148 104  80]
  [153 104  80]
  [164 116  88]]

 [[188 136 103]
  [180 129  98]
  [177 127  97]
  ...
  [149 103  79]
  [151 102  76]
  [168 119  90]]

 [[187 135 104]
  [186 133 102]
  [185 133 101]
  ...
  [139  92  70]
  [152 101  76]
  [170 121  91]]

 ...

 [[172 125  89]
  [172 129  94]
  [185 140 102]
  ...
  [179 131  97]
  [185 138 103]
  [191 144 109]]

 [[173 125  90]
  [170 127  93]
  [184 138 100]
  ...
  [176 127  95]
  [181 136 101]
  [183 139 105]]

 [[166 121  87]
  [169 126  93]
  [184 138 101]
  ...
  [174 127  94]
  [179 133  99]
  [178 136 103]]]
220 
 [[[157 112  84]
  [169 123  92]
  [186 137 104]
  ...
  [163 113  84]
  [148 105  81]
  [129  87  68]]

 [[159 115  86]
  [173 125  94]
  [193 144 108]
  ...
  [168 117  87]
  [153 110  84]
  [128  86  68]]

 [[165 118  88]
  [176 128  96]
  [195 143 107]
  ...
  [171 120  89]
  [157 114  87]
  [134  91  72]]

 ...

 [[188 135  94]
  [188 139  99]
  [192 1

60 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
70 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255

220 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
230 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

In [24]:
X = np.array(X)
Y = np.array(Y)

print(X.shape)
print(Y.shape)

(4277, 150, 150, 3)
(4277, 88)


In [25]:
x_train = X
y_train = Y

In [26]:
image_w = 150
image_h = 150

test_X = []
test_Y = []

for idx, cat in enumerate(categories):
    label = [0 for i in range(nb_classes)]
    label[idx] = 1
    
    files = glob(test_base_dir + '/' + cat + '/*.png')
    for i, f in enumerate(files):
        img = Image.open(f)
        img = img.convert('RGB')
        img = img.resize((image_w, image_h))
        data = np.asarray(img)
        test_X.append(data)
        test_Y.append(label)
        if i % 10 ==0:
            print(i, '\n', data)


0 
 [[[15 15 24]
  [15 14 27]
  [15 15 26]
  ...
  [15 15 25]
  [14 14 25]
  [14 14 24]]

 [[15 15 25]
  [15 15 26]
  [15 15 25]
  ...
  [15 15 25]
  [15 14 24]
  [14 14 24]]

 [[15 16 26]
  [16 15 25]
  [16 15 26]
  ...
  [15 15 25]
  [15 16 26]
  [14 14 25]]

 ...

 [[15 15 26]
  [15 15 26]
  [15 15 25]
  ...
  [17 18 26]
  [15 16 25]
  [15 15 25]]

 [[17 17 29]
  [16 16 27]
  [15 15 24]
  ...
  [16 17 26]
  [15 16 25]
  [14 15 25]]

 [[17 17 29]
  [16 16 26]
  [15 15 24]
  ...
  [14 15 26]
  [15 15 25]
  [15 15 25]]]
0 
 [[[12 12 22]
  [12 12 22]
  [13 12 22]
  ...
  [13 13 22]
  [13 12 21]
  [12 12 22]]

 [[13 13 22]
  [13 13 23]
  [13 12 22]
  ...
  [13 12 21]
  [12 12 21]
  [13 12 22]]

 [[13 14 24]
  [13 13 23]
  [13 13 23]
  ...
  [13 13 22]
  [13 12 21]
  [12 12 20]]

 ...

 [[13 12 22]
  [12 12 21]
  [12 12 21]
  ...
  [13 13 22]
  [13 13 22]
  [13 13 22]]

 [[12 12 21]
  [12 12 22]
  [12 12 21]
  ...
  [13 13 21]
  [12 13 22]
  [13 13 23]]

 [[12 12 21]
  [12 12 21]
  [13 12

40 
 [[[ 68  85 106]
  [ 72  91 111]
  [ 74  97 119]
  ...
  [ 75  98 122]
  [ 75  97 121]
  [ 70  87 110]]

 [[ 59  73  88]
  [ 71  90 110]
  [ 74  97 121]
  ...
  [ 76  98 124]
  [ 71  91 114]
  [ 65  79  99]]

 [[ 64  81  98]
  [ 70  89 111]
  [ 71  90 114]
  ...
  [ 71  90 115]
  [ 69  85 107]
  [ 67  84 103]]

 ...

 [[ 62  83 110]
  [ 60  80 108]
  [ 57  77 105]
  ...
  [ 63  80 101]
  [ 54  67  85]
  [ 58  72  88]]

 [[ 72  97 125]
  [ 68  92 118]
  [ 63  85 110]
  ...
  [ 60  76  95]
  [ 54  67  85]
  [ 58  72  89]]

 [[ 66  89 115]
  [ 61  80 102]
  [ 60  79  98]
  ...
  [ 57  71  88]
  [ 54  66  82]
  [ 59  73  91]]]
50 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0

40 
 [[[190 190 190]
  [190 190 190]
  [189 189 189]
  ...
  [191 191 191]
  [193 193 193]
  [191 191 191]]

 [[190 190 190]
  [191 191 191]
  [189 189 189]
  ...
  [190 190 190]
  [190 190 190]
  [190 190 190]]

 [[192 192 192]
  [192 192 192]
  [191 191 191]
  ...
  [190 190 190]
  [192 192 192]
  [192 192 192]]

 ...

 [[179 179 179]
  [179 179 179]
  [180 180 180]
  ...
  [184 184 184]
  [185 185 185]
  [185 185 185]]

 [[180 180 180]
  [180 180 180]
  [180 180 180]
  ...
  [184 184 184]
  [184 184 184]
  [184 184 184]]

 [[179 179 179]
  [178 178 178]
  [180 180 180]
  ...
  [186 186 186]
  [184 184 184]
  [184 184 184]]]
50 
 [[[13 14 23]
  [14 14 24]
  [14 13 24]
  ...
  [14 14 23]
  [13 13 22]
  [13 13 22]]

 [[13 13 23]
  [14 14 23]
  [14 13 23]
  ...
  [15 16 25]
  [14 14 23]
  [12 12 22]]

 [[13 13 23]
  [13 13 23]
  [13 13 24]
  ...
  [13 13 22]
  [13 12 23]
  [13 12 21]]

 ...

 [[13 13 23]
  [15 15 25]
  [16 15 25]
  ...
  [14 15 24]
  [13 13 23]
  [13 13 23]]

 [[13 13 2

30 
 [[[25 26 31]
  [24 26 32]
  [25 25 31]
  ...
  [25 24 30]
  [25 25 31]
  [25 25 31]]

 [[23 24 31]
  [24 25 31]
  [25 25 32]
  ...
  [25 25 31]
  [25 26 31]
  [25 25 31]]

 [[24 24 31]
  [25 25 32]
  [25 25 31]
  ...
  [25 25 31]
  [25 26 31]
  [24 24 30]]

 ...

 [[26 26 33]
  [25 25 33]
  [25 25 32]
  ...
  [25 24 30]
  [24 24 31]
  [26 25 31]]

 [[26 26 33]
  [25 26 33]
  [25 25 32]
  ...
  [24 24 31]
  [24 24 30]
  [25 24 31]]

 [[25 25 32]
  [24 25 30]
  [25 25 31]
  ...
  [23 24 30]
  [25 24 31]
  [25 25 31]]]
40 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
50 
 [[[16 15 28]
  [17 17 27]
  [16 16 26]
  ...
  [1

30 
 [[[108  72  61]
  [110  74  61]
  [141  93  75]
  ...
  [103  67  56]
  [ 95  61  51]
  [ 96  62  52]]

 [[129  85  70]
  [122  80  65]
  [126  82  66]
  ...
  [122  79  64]
  [111  71  59]
  [111  73  60]]

 [[122  79  65]
  [138  91  75]
  [123  82  67]
  ...
  [115  74  60]
  [116  75  62]
  [116  75  61]]

 ...

 [[ 83  56  50]
  [ 86  58  52]
  [ 90  60  52]
  ...
  [103  67  57]
  [ 89  59  51]
  [ 84  54  48]]

 [[ 98  66  56]
  [ 99  68  58]
  [103  70  59]
  ...
  [112  73  62]
  [104  69  59]
  [ 86  56  49]]

 [[ 96  64  56]
  [ 92  63  53]
  [ 92  62  53]
  ...
  [ 97  63  55]
  [106  70  60]
  [101  68  58]]]
40 
 [[[156 107  95]
  [158 108  95]
  [156 107  93]
  ...
  [159 108  95]
  [160 110  97]
  [157 109  95]]

 [[154 106  93]
  [157 107  94]
  [159 108  94]
  ...
  [159 109  95]
  [161 111  97]
  [160 110  95]]

 [[149 102  90]
  [153 105  91]
  [158 107  93]
  ...
  [162 111  96]
  [161 110  96]
  [161 110  96]]

 ...

 [[156 106  94]
  [155 105  93]
  [154 103

20 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
30 
 [[[14 15 29]
  [14 16 29]
  [13 15 29]
  ...
  [12 14 26]
  [13 14 28]
  [13 15 27]]

 [[14 15 29]
  [13 15 28]
  [14 15 29]
  ...
  [12 14 26]
  [12 14 27]
  [12 13 26]]

 [[14 15 29]
  [13 14 28]
  [14 15 29]
  ...
  [12 14 27]
  [11 14 26]
  [12 14 27]]

 ...

 [[14 15 28]
  [13 14 27]
  [13 15 28]
  ...
  [13 15 27]
  [13 14 27]
  [13 15 28]]

 [[13 14 28]
  [12 14 27]
  [13 15 28]
  ...
  [13 15 28]
  [13 15 27]
  [13 15 28]]

 [[13 15 29]
  [12 15 28]
  [13 15 28]
  ...
  [13 15 25]
  [13 15 26]
  [14 15 29]]]
40 
 [[[177 127  99]
  [171 124  98]
  [165 118  95]
 

10 
 [[[201 201 201]
  [198 198 198]
  [200 200 200]
  ...
  [209 209 209]
  [211 211 211]
  [211 211 211]]

 [[201 201 201]
  [201 201 201]
  [201 201 201]
  ...
  [211 211 211]
  [213 213 213]
  [212 212 212]]

 [[200 200 200]
  [201 201 201]
  [202 202 202]
  ...
  [211 211 211]
  [212 212 212]
  [212 212 212]]

 ...

 [[210 210 210]
  [211 211 211]
  [210 210 210]
  ...
  [205 205 205]
  [203 203 203]
  [203 203 203]]

 [[210 210 210]
  [211 211 211]
  [210 210 210]
  ...
  [204 204 204]
  [203 203 203]
  [203 203 203]]

 [[211 211 211]
  [210 210 210]
  [211 211 211]
  ...
  [205 205 205]
  [205 205 205]
  [204 204 204]]]
20 
 [[[197 202 200]
  [199 202 198]
  [200 203 201]
  ...
  [207 213 208]
  [208 214 210]
  [207 214 208]]

 [[199 203 199]
  [198 202 201]
  [201 203 200]
  ...
  [207 213 208]
  [207 214 209]
  [207 213 207]]

 [[199 202 200]
  [200 201 200]
  [199 201 199]
  ...
  [210 213 209]
  [207 215 208]
  [209 215 208]]

 ...

 [[211 213 217]
  [211 212 216]
  [213 213

0 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
0 
 [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [188 190 185]
  [187 188 182]
  [185 188 182]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [189 190 187]
  [187 190 186]
  [189 190 187]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..

20 
 [[[146 106  92]
  [146 107  93]
  [145 104  90]
  ...
  [148 108  92]
  [150 110  94]
  [147 108  92]]

 [[144 105  91]
  [144 105  90]
  [144 104  90]
  ...
  [152 111  95]
  [149 109  92]
  [147 107  91]]

 [[145 105  91]
  [146 107  90]
  [146 107  91]
  ...
  [153 113  95]
  [151 111  92]
  [149 109  92]]

 ...

 [[134 100  88]
  [135  99  87]
  [132  98  86]
  ...
  [141 104  87]
  [143 104  88]
  [146 106  91]]

 [[136 100  87]
  [134  99  87]
  [133  99  87]
  ...
  [142 103  87]
  [141 103  87]
  [144 106  90]]

 [[135 100  88]
  [134  99  88]
  [134  99  85]
  ...
  [142 104  88]
  [142 104  88]
  [144 106  91]]]
30 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0

50 
 [[[42 42 46]
  [41 41 45]
  [41 42 47]
  ...
  [42 40 46]
  [42 40 45]
  [42 40 45]]

 [[41 41 46]
  [42 41 47]
  [42 42 46]
  ...
  [41 41 46]
  [42 41 46]
  [41 40 45]]

 [[42 42 47]
  [42 42 47]
  [41 41 46]
  ...
  [41 41 46]
  [42 42 47]
  [41 41 46]]

 ...

 [[44 45 49]
  [45 46 47]
  [44 43 47]
  ...
  [42 41 45]
  [41 41 44]
  [41 41 44]]

 [[42 44 46]
  [43 43 45]
  [42 43 47]
  ...
  [41 41 44]
  [41 41 42]
  [41 41 43]]

 [[43 44 45]
  [42 43 46]
  [42 43 46]
  ...
  [40 40 44]
  [40 40 43]
  [40 40 43]]]
60 
 [[[185 189 181]
  [190 194 188]
  [189 194 190]
  ...
  [175 178 171]
  [174 177 173]
  [172 174 168]]

 [[162 161 157]
  [162 164 160]
  [181 185 180]
  ...
  [155 155 152]
  [176 176 170]
  [172 173 165]]

 [[150 148 143]
  [156 158 152]
  [183 188 185]
  ...
  [146 146 141]
  [173 172 166]
  [174 174 165]]

 ...

 [[175 182 162]
  [144 148 133]
  [117 119 106]
  ...
  [ 71  70  66]
  [ 72  73  69]
  [ 73  72  67]]

 [[174 181 163]
  [158 163 146]
  [141 145 129

40 
 [[[16 17 22]
  [17 17 23]
  [16 16 22]
  ...
  [20 19 25]
  [19 18 25]
  [19 19 24]]

 [[16 17 22]
  [17 16 23]
  [15 16 23]
  ...
  [19 18 25]
  [19 17 25]
  [19 18 24]]

 [[17 17 22]
  [16 16 24]
  [16 16 23]
  ...
  [19 18 25]
  [19 18 26]
  [19 18 25]]

 ...

 [[19 18 23]
  [19 18 23]
  [18 18 23]
  ...
  [17 17 23]
  [17 17 23]
  [17 16 22]]

 [[18 18 23]
  [19 18 24]
  [18 18 23]
  ...
  [17 17 23]
  [18 18 23]
  [17 17 22]]

 [[18 18 23]
  [18 18 23]
  [18 18 23]
  ...
  [16 16 21]
  [16 17 22]
  [16 17 22]]]
50 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
60 
 [[[151 155 144]
  [137 140 130]
  [147 150 138]
 

30 
 [[[152 148 140]
  [145 145 137]
  [166 167 156]
  ...
  [ 65  64  60]
  [101 102  93]
  [147 156 142]]

 [[171 170 165]
  [165 164 160]
  [156 154 149]
  ...
  [ 86  83  75]
  [105 105  95]
  [132 137 127]]

 [[136 132 129]
  [140 135 130]
  [118 110 105]
  ...
  [ 93  93  84]
  [ 94  93  84]
  [ 99  97  89]]

 ...

 [[149 143 136]
  [146 142 137]
  [159 161 155]
  ...
  [123 122 112]
  [145 146 135]
  [149 151 140]]

 [[171 166 162]
  [173 170 165]
  [179 181 175]
  ...
  [139 140 129]
  [142 144 132]
  [144 146 137]]

 [[163 159 150]
  [174 173 164]
  [183 184 176]
  ...
  [144 144 134]
  [116 116 105]
  [123 125 114]]]
0 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 

0 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
0 
 [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [208 208 208]
  [209 209 209]
  [196 196 196]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [206 206 206]
  [207 207 207]
  [208 208 208]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [206 206 206]
  [208 208 208]
  [210 210 210]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ..

0 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
0 
 [[[25 25 31]
  [24 25 30]
  [25 25 31]
  ...
  [23 23 31]
  [24 22 30]
  [23 23 30]]

 [[25 25 31]
  [24 25 32]
  [26 25 31]
  ...
  [23 24 31]
  [23 24 30]
  [23 24 30]]

 [[24 25 32]
  [25 25 31]
  [26 25 31]
  ...
  [23 24 31]
  [23 24 30]
  [25 23 30]]

 ...

 [[24 24 30]
  [25 25 31]
  [24 25 31]
  ...
  [24 24 31]
  [23 24 31]
  [24 24 31]]

 [[25 25 31]
  [25 25 31]
  [25 25 32]
  ...
  [24 24 31]
  [25 24 31]
  [24 25 31]]

 [[25 25 32]
  [26 25 31]
  [27 25 31]
  ...
  [24 24 30]
  [25 24 31]
  [25 24 31]]]
0 
 [[[132 135 125]
  [127 132 120]
  [135 139 129]
  ..

110 
 [[[108  71  60]
  [ 97  63  54]
  [102  66  57]
  ...
  [ 91  58  49]
  [ 98  64  54]
  [ 87  56  48]]

 [[104  69  60]
  [ 96  61  53]
  [111  73  61]
  ...
  [ 93  61  51]
  [ 90  56  48]
  [ 97  62  52]]

 [[123  81  68]
  [103  66  57]
  [ 98  62  55]
  ...
  [112  74  62]
  [ 86  57  50]
  [ 93  58  49]]

 ...

 [[ 85  58  51]
  [102  69  59]
  [103  70  59]
  ...
  [104  67  58]
  [110  72  61]
  [106  69  58]]

 [[ 87  59  51]
  [ 84  56  50]
  [ 88  60  52]
  ...
  [113  73  62]
  [110  72  61]
  [103  67  58]]

 [[107  72  62]
  [ 99  67  58]
  [107  72  61]
  ...
  [104  68  58]
  [ 97  63  54]
  [ 93  60  51]]]
120 
 [[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[41 41 45]
  [42 42 46]
  [42 41 46]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[41 42

In [27]:
test_x = np.array(test_X)
y_test = np.array(test_Y)

print(test_x.shape)
print(y_test.shape)

(2154, 150, 150, 3)
(2154, 88)


In [28]:
x_train = x_train.astype('float') / 255
x_test = test_x.astype('float') / 255

In [29]:
y_train.argmax(1)

array([ 0,  0,  0, ..., 87, 87, 87], dtype=int64)

In [30]:
print(x_train.shape)
print(y_train.shape)

(4277, 150, 150, 3)
(4277, 88)


In [46]:
for i,fname in enumerate(os.listdir(test_base_dir)):
    print('클래스:{}, 이미지 수 :{}'.format(i, len(os.listdir(test_base_dir + '/'+fname))))
        

클래스:0, 이미지 수 :8
클래스:1, 이미지 수 :7
클래스:2, 이미지 수 :6
클래스:3, 이미지 수 :112
클래스:4, 이미지 수 :4
클래스:5, 이미지 수 :3
클래스:6, 이미지 수 :2
클래스:7, 이미지 수 :4
클래스:8, 이미지 수 :3
클래스:9, 이미지 수 :103
클래스:10, 이미지 수 :4
클래스:11, 이미지 수 :2
클래스:12, 이미지 수 :3
클래스:13, 이미지 수 :6
클래스:14, 이미지 수 :6
클래스:15, 이미지 수 :110
클래스:16, 이미지 수 :5
클래스:17, 이미지 수 :5
클래스:18, 이미지 수 :4
클래스:19, 이미지 수 :6
클래스:20, 이미지 수 :4
클래스:21, 이미지 수 :147
클래스:22, 이미지 수 :5
클래스:23, 이미지 수 :7
클래스:24, 이미지 수 :4
클래스:25, 이미지 수 :2
클래스:26, 이미지 수 :3
클래스:27, 이미지 수 :4
클래스:28, 이미지 수 :131
클래스:29, 이미지 수 :2
클래스:30, 이미지 수 :4
클래스:31, 이미지 수 :3
클래스:32, 이미지 수 :5
클래스:33, 이미지 수 :185
클래스:34, 이미지 수 :6
클래스:35, 이미지 수 :4
클래스:36, 이미지 수 :4
클래스:37, 이미지 수 :6
클래스:38, 이미지 수 :2
클래스:39, 이미지 수 :5
클래스:40, 이미지 수 :125
클래스:41, 이미지 수 :4
클래스:42, 이미지 수 :7
클래스:43, 이미지 수 :6
클래스:44, 이미지 수 :5
클래스:45, 이미지 수 :127
클래스:46, 이미지 수 :4
클래스:47, 이미지 수 :8
클래스:48, 이미지 수 :4
클래스:49, 이미지 수 :6
클래스:50, 이미지 수 :6
클래스:51, 이미지 수 :8
클래스:52, 이미지 수 :130
클래스:53, 이미지 수 :4
클래스:54, 이미지 수 :7
클래스:55, 이미지 수 :153
클래스:56, 이미지 수 :8
클래스:57, 이미지 수 :5
클래스:

In [48]:
skf = StratifiedKFold(n_splits = 15, random_state = 32, shuffle = True)
n = 0

cnn_pred = []

for train_index, valid_index in skf.split(x_train, y_train.argmax(1)):
    n += 1
    x_train, x_valid = x_train[train_index], x_train[valid_index]
    y_train, y_valid = y_train[train_index], y_train[valid_index]
    
    model = CustomModel()
    
    model.compile(optimizer = 'Adam', 
                  loss = 'categorical_crossentropy', 
                  metrics = ['accuracy'])
    
    filename = 'CNN_checkpoint3.h5'
    checkpoint = tf.keras.callbacks.ModelCheckpoint(filename,
                                                   monitor = 'val_accuracy',
                                                   verbose = 0,
                                                   save_best_only = True,
                                                   mode = 'auto')

    earlystopping = tf.keras.callbacks.EarlyStopping(monitor = 'val_accuracy',
                                                    patience = 6)
    
    train_datagen = ImageDataGenerator(rescale = 1./255,
                                        rotation_range = 40,
                                        width_shift_range = 0.2,
                                        height_shift_range = 0.2,
                                        shear_range = 0.2,
                                        zoom_range = 0.2,
                                        horizontal_flip = True)
    
    test_datagen = ImageDataGenerator(rescale = 1./255)
    
    valid_datagen = ImageDataGenerator(rescale = 1./255)

    train_generator = train_datagen.flow_from_directory(
        base_dir,
        target_size = (150,150),
        batch_size = 40,
        class_mode = 'categorical')
    
    valid_generator = test_datagen.flow_from_directory(
        test_base_dir,
        target_size = (150,150),
        batch_size = 40,
        class_mode = 'categorical')
        
    history = model.fit_generator(
    train_generator,
    steps_per_epoch = 100,
    epochs = 10,
    validation_data = valid_generator,
    validation_steps = 40,
    callbacks = [checkpoint, earlystopping])
    

C:\Users\choij\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=15.
  warnings.warn(("The least populated class in y has only %d"


Found 4277 images belonging to 88 classes.
Found 2154 images belonging to 88 classes.


<ipython-input-48-5a6faa8afd4c>:51: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history = model.fit_generator(


Epoch 1/10
100/100 [==============================] - 158s 2s/step - loss: 1.7534 - accuracy: 0.7043 - val_loss: 4.8242 - val_accuracy: 0.0675
Epoch 2/10
100/100 [==============================] - 146s 1s/step - loss: 1.0871 - accuracy: 0.8224 - val_loss: 5.3524 - val_accuracy: 0.0669
Epoch 3/10
100/100 [==============================] - 149s 1s/step - loss: 0.9096 - accuracy: 0.8359 - val_loss: 6.2336 - val_accuracy: 0.0694
Epoch 4/10
100/100 [==============================] - 154s 2s/step - loss: 0.8550 - accuracy: 0.8351 - val_loss: 6.6606 - val_accuracy: 0.0594
Epoch 5/10
100/100 [==============================] - 147s 1s/step - loss: 0.7997 - accuracy: 0.8401 - val_loss: 7.4565 - val_accuracy: 0.0512
Epoch 6/10
100/100 [==============================] - 147s 1s/step - loss: 0.7912 - accuracy: 0.8394 - val_loss: 10.4868 - val_accuracy: 0.0581
Epoch 7/10
100/100 [==============================] - 149s 1s/step - loss: 0.7595 - accuracy: 0.8414 - val_loss: 9.2524 - val_accuracy: 0.052

IndexError: index 3724 is out of bounds for axis 0 with size 3724